name: Deploy Band Manager App
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
        env:
          CI: false
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
          REACT_APP_COMPANY_NAME: ${{ secrets.REACT_APP_COMPANY_NAME }}
          REACT_APP_COMPANY_ADDRESS: ${{ secrets.REACT_APP_COMPANY_ADDRESS }}
          REACT_APP_COMPANY_EMAIL: ${{ secrets.REACT_APP_COMPANY_EMAIL }}
          REACT_APP_COMPANY_PHONE: ${{ secrets.REACT_APP_COMPANY_PHONE }}
          REACT_APP_HOSTING_PROVIDER: ${{ secrets.REACT_APP_HOSTING_PROVIDER }}

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Deploy to shared hosting
        run: |
          rsync -avz -v --delete -e "ssh -i ~/.ssh/deploy_key -p ${{ secrets.SSH_PORT }} -v" \
          build/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_PATH }}
